/**
 * cols_meta.js — Metadatos de columnas de AmecoDashboards
 * Cargado por diccionario.html y requerimientos.html
 */
window.COLS_META = [
  // ── Orden de Trabajo ──
  { campo:"OrdenTrabajoId",                              original:"id",                                          tabla:"ordenTrabajo",                         tipo:"INT",      grupo:"Orden de Trabajo",    nota:"" },
  { campo:"OrdenTrabajoFechaInicio",                     original:"fechaInicio",                                 tabla:"ordenTrabajo",                         tipo:"DATETIME", grupo:"Orden de Trabajo",    nota:"" },
  { campo:"OrdenTrabajoDescripcion",                     original:"descripcion",                                 tabla:"ordenTrabajo",                         tipo:"NVARCHAR", grupo:"Orden de Trabajo",    nota:"" },
  { campo:"OrdenTrabajoFechaFin",                        original:"fechaFin",                                    tabla:"ordenTrabajo",                         tipo:"DATETIME", grupo:"Orden de Trabajo",    nota:"Fecha planificada de cierre OT" },
  { campo:"OrdenTrabajoFechaInicioReal",                 original:"fechaInicioReal",                             tabla:"ordenTrabajo",                         tipo:"DATETIME", grupo:"Orden de Trabajo",    nota:"" },
  { campo:"OrdenTrabajoFechaFinReal",                    original:"fechaFinReal",                                tabla:"ordenTrabajo",                         tipo:"DATETIME", grupo:"Orden de Trabajo",    nota:"Fecha real de cierre — clave para SLA" },
  { campo:"OrdenTrabajoTiempoResolucionBruto",           original:"tiempoResolucionBruto",                       tabla:"ordenTrabajo",                         tipo:"INT",      grupo:"Orden de Trabajo",    nota:"Minutos" },
  { campo:"OrdenTrabajoDuracion",                        original:"duracion",                                    tabla:"ordenTrabajo",                         tipo:"INT",      grupo:"Orden de Trabajo",    nota:"" },
  { campo:"OrdenTrabajoFechaCreacion",                   original:"fechaCreacion",                               tabla:"ordenTrabajo",                         tipo:"DATETIME", grupo:"Orden de Trabajo",    nota:"" },
  { campo:"OrdenTrabajoUbicacion",                       original:"ubicacion",                                   tabla:"ordenTrabajo",                         tipo:"NVARCHAR", grupo:"Orden de Trabajo",    nota:"" },
  { campo:"OrdenTrabajoNochero",                         original:"nochero",                                     tabla:"ordenTrabajo",                         tipo:"BIT",      grupo:"Orden de Trabajo",    nota:"" },
  { campo:"TipoActividadId",                             original:"id",                                          tabla:"tipoActividad",                        tipo:"INT",      grupo:"Orden de Trabajo",    nota:"" },
  { campo:"TipoActividad",                               original:"nombreReal",                                  tabla:"tipoActividad",                        tipo:"NVARCHAR", grupo:"Orden de Trabajo",    nota:"Ej: Backlog, Correctivo menor, PM" },
  { campo:"OrdenTrabajoPlanId",                          original:"planId",                                      tabla:"ordenTrabajo",                         tipo:"INT",      grupo:"Orden de Trabajo",    nota:"" },
  { campo:"OrdenTrabajoPlanNombre",                      original:"nombre",                                      tabla:"plan",                                 tipo:"NVARCHAR", grupo:"Proceso & Plan",      nota:"" },
  { campo:"OrdenTrabajoEmpresa",                         original:"nombre",                                      tabla:"empresa",                              tipo:"NVARCHAR", grupo:"Orden de Trabajo",    nota:"" },
  { campo:"OrdenTrabajoNegocio",                         original:"nombre",                                      tabla:"negocio",                              tipo:"NVARCHAR", grupo:"Clasificación",       nota:"" },
  { campo:"OrdenTrabajoSolicitante",                     original:"nombre",                                      tabla:"persona",                              tipo:"NVARCHAR", grupo:"OT Personas",         nota:"" },
  { campo:"OrdenTrabajoResponsable",                     original:"nombre",                                      tabla:"persona",                              tipo:"NVARCHAR", grupo:"OT Personas",         nota:"" },
  { campo:"EstadoOrdenTrabajoId",                        original:"id",                                          tabla:"estadoOt",                             tipo:"INT",      grupo:"Orden de Trabajo",    nota:"" },
  { campo:"EstadoOrdenTrabajo",                          original:"nombre",                                      tabla:"estadoOt",                             tipo:"NVARCHAR", grupo:"Orden de Trabajo",    nota:"" },
  // ── Operación ──
  { campo:"OperacionId",                                 original:"id",                                          tabla:"operacion",                            tipo:"INT",      grupo:"Operación",           nota:"" },
  { campo:"OperacionDescripcion",                        original:"descripcion",                                 tabla:"operacion",                            tipo:"NVARCHAR", grupo:"Operación",           nota:"" },
  { campo:"OperacionTiempoEstandar",                     original:"duracionMinSTD",                              tabla:"operacion",                            tipo:"INT",      grupo:"Operación",           nota:"Minutos" },
  { campo:"OperacionTiempoDuracionReal",                 original:"duracionReal",                                tabla:"operacion",                            tipo:"INT",      grupo:"Operación",           nota:"Minutos" },
  { campo:"OperacionTiempoPerdido",                      original:"tiempoPerdidoMin",                            tabla:"operacion",                            tipo:"INT",      grupo:"Operación",           nota:"ISNULL → 0" },
  { campo:"OperacionFechaResolucion",                    original:"fechaResolucion",                             tabla:"operacion",                            tipo:"DATETIME", grupo:"Operación",           nota:"" },
  { campo:"OperacionSolucionComentario",                 original:"detalleSolucion",                             tabla:"operacion",                            tipo:"NVARCHAR", grupo:"Operación",           nota:"" },
  { campo:"OperacionTiempoEstandarCumplido",             original:"cumpleSTD",                                   tabla:"operacion",                            tipo:"BIT",      grupo:"Operación",           nota:"" },
  { campo:"OperacionRequiereMateriales",                 original:"requiereMateriales",                          tabla:"operacion",                            tipo:"BIT",      grupo:"Operación",           nota:"" },
  { campo:"OperacionUbicacion",                          original:"ubicacion",                                   tabla:"operacion",                            tipo:"NVARCHAR", grupo:"Operación",           nota:"" },
  { campo:"OperacionRecursos",                           original:"recursos",                                    tabla:"operacion",                            tipo:"NVARCHAR", grupo:"Operación",           nota:"" },
  { campo:"OperacionMovilizacion",                       original:"movilizacion",                                tabla:"operacion",                            tipo:"NVARCHAR", grupo:"Operación",           nota:"" },
  { campo:"OperacionSecuencia",                          original:"secuencia",                                   tabla:"operacion",                            tipo:"INT",      grupo:"Operación",           nota:"" },
  { campo:"OperacionDependencia",                        original:"dependencia",                                 tabla:"operacion",                            tipo:"NVARCHAR", grupo:"Operación",           nota:"" },
  { campo:"OperacionOrden",                              original:"orden",                                       tabla:"operacion",                            tipo:"INT",      grupo:"Operación",           nota:"" },
  { campo:"OperacionPlazo",                              original:"plazo",                                       tabla:"operacion",                            tipo:"INT",      grupo:"Operación",           nota:"" },
  { campo:"OperacionTrabajo",                            original:"trabajo",                                     tabla:"operacion",                            tipo:"NVARCHAR", grupo:"Operación",           nota:"" },
  { campo:"OperacionPrecio1",                            original:"precio1",                                     tabla:"operacion",                            tipo:"DECIMAL",  grupo:"Operación",           nota:"DECIMAL(18,2)" },
  { campo:"OperacionPrecio2",                            original:"precio2",                                     tabla:"operacion",                            tipo:"DECIMAL",  grupo:"Operación",           nota:"DECIMAL(18,2)" },
  { campo:"OperacionLatitud",                            original:"latitud",                                     tabla:"operacion",                            tipo:"DECIMAL",  grupo:"Operación",           nota:"DECIMAL(10,7)" },
  { campo:"OperacionLongitud",                           original:"longitud",                                    tabla:"operacion",                            tipo:"DECIMAL",  grupo:"Operación",           nota:"DECIMAL(10,7)" },
  { campo:"OperacionDireccion",                          original:"direccion",                                   tabla:"operacion",                            tipo:"NVARCHAR", grupo:"Operación",           nota:"" },
  { campo:"OperacionTiempoTraslado",                     original:"duracionTraslado",                            tabla:"operacion",                            tipo:"INT",      grupo:"Operación",           nota:"Minutos" },
  { campo:"OperacionElementoLinea",                      original:"elementoLinea",                               tabla:"operacion",                            tipo:"NVARCHAR", grupo:"Operación",           nota:"" },
  { campo:"OperacionElementoCodigo",                     original:"elementoCodigo",                              tabla:"operacion",                            tipo:"NVARCHAR", grupo:"Operación",           nota:"" },
  { campo:"OperacionElementoDescripcion",                original:"elementoDescripcion",                         tabla:"operacion",                            tipo:"NVARCHAR", grupo:"Operación",           nota:"" },
  { campo:"OperacionRequiereAprobacion",                 original:"requiereAprobacion",                          tabla:"operacion",                            tipo:"BIT",      grupo:"Operación",           nota:"" },
  { campo:"OperacionEvidenciaFlag",                      original:"evidenciaFlag",                               tabla:"operacion",                            tipo:"BIT",      grupo:"Operación",           nota:"" },
  { campo:"OperacionSecuenciadorFlag",                   original:"secuenciadorFlag",                            tabla:"operacion",                            tipo:"BIT",      grupo:"Operación",           nota:"" },
  { campo:"OperacionProcesoId",                          original:"procesoOperacionId",                          tabla:"operacion",                            tipo:"INT",      grupo:"Operación",           nota:"" },
  { campo:"OperacionPadreId",                            original:"operacionPadreId",                            tabla:"operacion",                            tipo:"INT",      grupo:"Operación",           nota:"NULL = operación raíz de la OT" },
  { campo:"OperacionFechaFin",                           original:"fechaFin",                                    tabla:"operacion",                            tipo:"DATETIME", grupo:"Operación - Fechas",  nota:"" },
  { campo:"OperacionFechaAgendada",                      original:"fechaAgendada",                               tabla:"operacion",                            tipo:"DATETIME", grupo:"Operación - Fechas",  nota:"" },
  { campo:"OperacionFechaProgramada",                    original:"fechaProgramada",                             tabla:"operacion",                            tipo:"DATETIME", grupo:"Operación - Fechas",  nota:"" },
  { campo:"OperacionFechaAsignacion",                    original:"fechaAsignacion",                             tabla:"operacion",                            tipo:"DATETIME", grupo:"Operación - Fechas",  nota:"" },
  { campo:"OperacionFechaLiberacion",                    original:"fechaLiberacion",                             tabla:"operacion",                            tipo:"DATETIME", grupo:"Operación - Fechas",  nota:"" },
  { campo:"OperacionFechaDesasignacion",                 original:"fechaDesasignacion",                          tabla:"operacion",                            tipo:"DATETIME", grupo:"Operación - Fechas",  nota:"" },
  { campo:"OperacionFechaDetenidoInicio",                original:"fechaDetenidoInicio",                         tabla:"operacion",                            tipo:"DATETIME", grupo:"Operación - Fechas",  nota:"" },
  { campo:"OperacionFechaDetenidoFin",                   original:"fechaDetenidoFin",                            tabla:"operacion",                            tipo:"DATETIME", grupo:"Operación - Fechas",  nota:"" },
  { campo:"OperacionFechaInicio",                        original:"fechaInicioTareaReal / fechaInicio",          tabla:"operacionResolucion / operacion",       tipo:"DATETIME", grupo:"Operación - Fechas",  nota:"ISNULL en cascada: operesol → ope → ot" },
  // ── Clasificación ──
  { campo:"TipoTareaId",                                 original:"id",                                          tabla:"tipoTarea",                            tipo:"INT",      grupo:"Clasificación",       nota:"" },
  { campo:"TipoTarea",                                   original:"nombre",                                      tabla:"tipoTarea",                            tipo:"NVARCHAR", grupo:"Clasificación",       nota:"Nivel 1 de jerarquía" },
  { campo:"SubTipoTareaId",                              original:"id",                                          tabla:"subtipoTarea",                         tipo:"INT",      grupo:"Clasificación",       nota:"" },
  { campo:"SubTipoTarea",                                original:"nombre",                                      tabla:"subtipoTarea",                         tipo:"NVARCHAR", grupo:"Clasificación",       nota:"Nivel 2 — Entidad en el PPT" },
  { campo:"Nivel3Id",                                    original:"id",                                          tabla:"nivel3",                               tipo:"INT",      grupo:"Clasificación",       nota:"" },
  { campo:"Nivel3",                                      original:"nombre",                                      tabla:"nivel3",                               tipo:"NVARCHAR", grupo:"Clasificación",       nota:"Nivel 3 — Componente" },
  { campo:"Nivel4Id",                                    original:"id",                                          tabla:"nivel4",                               tipo:"INT",      grupo:"Clasificación",       nota:"" },
  { campo:"Nivel4",                                      original:"nombre",                                      tabla:"nivel4",                               tipo:"NVARCHAR", grupo:"Clasificación",       nota:"Nivel 4 — Acción" },
  { campo:"TipoOperacionId",                             original:"id",                                          tabla:"tipoOperacion",                        tipo:"INT",      grupo:"Clasificación",       nota:"" },
  { campo:"TipoOperacion",                               original:"nombre",                                      tabla:"tipoOperacion",                        tipo:"NVARCHAR", grupo:"Clasificación",       nota:"" },
  { campo:"EspecialidadId",                              original:"id",                                          tabla:"especialidad",                         tipo:"INT",      grupo:"Clasificación",       nota:"" },
  { campo:"Especialidad",                                original:"nombre",                                      tabla:"especialidad",                         tipo:"NVARCHAR", grupo:"Clasificación",       nota:"" },
  // ── Estado & Motivos ──
  { campo:"EstadoOperacionId",                           original:"id",                                          tabla:"estadoOperacion",                      tipo:"INT",      grupo:"Estado & Motivos",    nota:"" },
  { campo:"EstadoOperacion",                             original:"nombre",                                      tabla:"estadoOperacion",                      tipo:"NVARCHAR", grupo:"Estado & Motivos",    nota:"" },
  { campo:"MotivoDetencionId",                           original:"id",                                          tabla:"motivo",                               tipo:"INT",      grupo:"Estado & Motivos",    nota:"" },
  { campo:"MotivoDetencion",                             original:"valor",                                       tabla:"motivo",                               tipo:"NVARCHAR", grupo:"Estado & Motivos",    nota:"" },
  { campo:"MotivoDetencionTipo",                         original:"nombre",                                      tabla:"motivoTipo",                           tipo:"NVARCHAR", grupo:"Estado & Motivos",    nota:"" },
  { campo:"MotivoNoEjecucionId",                         original:"id",                                          tabla:"motivo",                               tipo:"INT",      grupo:"Estado & Motivos",    nota:"" },
  { campo:"MotivoNoEjecucion",                           original:"valor",                                       tabla:"motivo",                               tipo:"NVARCHAR", grupo:"Estado & Motivos",    nota:"" },
  // ── Resolutor ──
  { campo:"GrupoResolutorOperacionId",                   original:"id",                                          tabla:"grupoResolutor",                       tipo:"INT",      grupo:"Resolutor",           nota:"" },
  { campo:"GrupoResolutorOperacion",                     original:"nombre",                                      tabla:"grupoResolutor",                       tipo:"NVARCHAR", grupo:"Resolutor",           nota:"" },
  { campo:"OperacionResolutor",                          original:"nombre",                                      tabla:"persona",                              tipo:"NVARCHAR", grupo:"Resolutor",           nota:"" },
  { campo:"OperacionResolutorTurno",                     original:"nombre",                                      tabla:"turno",                                tipo:"NVARCHAR", grupo:"Resolutor",           nota:"ISNULL → 'Sin asignar'" },
  { campo:"OperacionResolutorCargo",                     original:"nombre",                                      tabla:"cargoResolutor",                       tipo:"NVARCHAR", grupo:"Resolutor",           nota:"" },
  // ── Ubicación ──
  { campo:"SitioOperacionId",                            original:"id",                                          tabla:"sitio",                                tipo:"INT",      grupo:"Ubicación",           nota:"" },
  { campo:"SitioOperacion",                              original:"nombre",                                      tabla:"sitio",                                tipo:"NVARCHAR", grupo:"Ubicación",           nota:"" },
  { campo:"ZonaOperacionId",                             original:"id",                                          tabla:"zona",                                 tipo:"INT",      grupo:"Ubicación",           nota:"" },
  { campo:"ZonaOperacion",                               original:"nombre",                                      tabla:"zona",                                 tipo:"NVARCHAR", grupo:"Ubicación",           nota:"" },
  { campo:"PrioridadOperacionId",                        original:"id",                                          tabla:"prioridad",                            tipo:"INT",      grupo:"Ubicación",           nota:"" },
  { campo:"PrioridadOperacion",                          original:"nombre",                                      tabla:"prioridad",                            tipo:"NVARCHAR", grupo:"Ubicación",           nota:"" },
  // ── Resolución ──
  { campo:"OperacionResolucionTiempoEspera",             original:"tiempoEspera",                                tabla:"operacionResolucion",                  tipo:"INT",      grupo:"Resolución",          nota:"Minutos" },
  { campo:"OperacionResolucionTiempoEjecucion",          original:"duracionEjecucion",                           tabla:"operacionResolucion",                  tipo:"INT",      grupo:"Resolución",          nota:"Minutos" },
  { campo:"OperacionResolucionTiempoBruto",              original:"tiempoResolucionBruto",                       tabla:"operacionResolucion",                  tipo:"INT",      grupo:"Resolución",          nota:"Minutos" },
  { campo:"OperacionResolucionTiempoTraslado",           original:"tiempoTrasladoDeclarado",                     tabla:"operacionResolucion",                  tipo:"INT",      grupo:"Resolución",          nota:"Minutos" },
  { campo:"OperacionResolucionTiemposAdministrativos",   original:"tiemposAdministrativos",                      tabla:"operacionResolucion",                  tipo:"INT",      grupo:"Resolución",          nota:"Minutos" },
  { campo:"OperacionResolucionNoEjecutada",              original:"noEjecutada",                                 tabla:"operacionResolucion",                  tipo:"BIT",      grupo:"Resolución",          nota:"" },
  { campo:"OperacionResolucionOrdenTrabajoAbortada",     original:"otAbortada",                                  tabla:"operacionResolucion",                  tipo:"BIT",      grupo:"Resolución",          nota:"" },
  { campo:"OperacionResolucionCumpleEstandares",         original:"cumpleEstandares",                            tabla:"operacionResolucion",                  tipo:"BIT",      grupo:"Resolución",          nota:"" },
  { campo:"OperacionResolucionEsPreparacionDoc",         original:"esPreparacionDocumentacion",                  tabla:"operacionResolucion",                  tipo:"BIT",      grupo:"Resolución",          nota:"" },
  { campo:"OperacionResolucionEsObtencionAutorizaciones",original:"esObtencionAutorizaciones",                   tabla:"operacionResolucion",                  tipo:"BIT",      grupo:"Resolución",          nota:"" },
  { campo:"OperacionResolucionEsObtencionPermisos",      original:"esObtencionPermisosES",                       tabla:"operacionResolucion",                  tipo:"BIT",      grupo:"Resolución",          nota:"" },
  { campo:"OperacionResolucionTipoFallaId",              original:"tipoFallaId",                                 tabla:"operacionResolucion",                  tipo:"INT",      grupo:"Resolución",          nota:"" },
  { campo:"OperacionResolucionLatitud",                  original:"latitud",                                     tabla:"operacionResolucion",                  tipo:"DECIMAL",  grupo:"Resolución",          nota:"DECIMAL(10,7)" },
  { campo:"OperacionResolucionLongitud",                 original:"longitud",                                    tabla:"operacionResolucion",                  tipo:"DECIMAL",  grupo:"Resolución",          nota:"DECIMAL(10,7)" },
  { campo:"OperacionResolucionFecha",                    original:"fechaResolucion",                             tabla:"operacionResolucion",                  tipo:"DATETIME", grupo:"Resolución",          nota:"" },
  // ── Activo ──
  { campo:"ActivoId",                                    original:"id",                                          tabla:"activo",                               tipo:"INT",      grupo:"Activo",              nota:"" },
  { campo:"Activo",                                      original:"nombre",                                      tabla:"activo",                               tipo:"NVARCHAR", grupo:"Activo",              nota:"" },
  { campo:"ActivoCodigo",                                original:"codigo",                                      tabla:"activo",                               tipo:"NVARCHAR", grupo:"Activo",              nota:"" },
  { campo:"ActivoElementoId",                            original:"id",                                          tabla:"activoElementos",                      tipo:"INT",      grupo:"Activo",              nota:"" },
  { campo:"ActivoElementoCodigo",                        original:"codigo",                                      tabla:"activoElementos",                      tipo:"NVARCHAR", grupo:"Activo",              nota:"" },
  { campo:"ActivoElementoHabitacion",                    original:"habitacion",                                  tabla:"activoElementos",                      tipo:"NVARCHAR", grupo:"Activo",              nota:"" },
  { campo:"ActivoElementoTipoInstalacion",               original:"tipoInstalacion",                             tabla:"activoElementos",                      tipo:"NVARCHAR", grupo:"Activo",              nota:"" },
  // ── Proceso & Plan ──
  { campo:"ProcesoId",                                   original:"id",                                          tabla:"proceso",                              tipo:"INT",      grupo:"Proceso & Plan",      nota:"" },
  { campo:"Proceso",                                     original:"nombre",                                      tabla:"proceso",                              tipo:"NVARCHAR", grupo:"Proceso & Plan",      nota:"" },
  // ── Instalación ──
  { campo:"EstadoInstalacionId",                         original:"id",                                          tabla:"estadoInstalacion",                    tipo:"INT",      grupo:"Instalación",         nota:"" },
  { campo:"EstadoInstalacion",                           original:"nombre",                                      tabla:"estadoInstalacion",                    tipo:"NVARCHAR", grupo:"Instalación",         nota:"" },
  { campo:"RecintoId",                                   original:"id",                                          tabla:"recinto",                              tipo:"INT",      grupo:"Instalación",         nota:"" },
  { campo:"Recinto",                                     original:"nombre",                                      tabla:"recinto",                              tipo:"NVARCHAR", grupo:"Instalación",         nota:"" },
];
