# Basado en la imagen que YA funciona en Azure
FROM acrsuper1284.azurecr.io/superset-mssql:latest

USER root

# Copiar configuración de producción
COPY superset_config_prod.py /app/pythonpath/superset_config.py

USER superset
