version: "3.8"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_DB: superset
    volumes:
      - db_data:/var/lib/postgresql/data

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "AmecoSQL2024!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_AGENT_ENABLED: "true"
    volumes:
      - sqlserver_data:/var/opt/mssql

  superset:
    build: .
    image: acrsuper1284.azurecr.io/superset-mssql:6.1.0
    restart: unless-stopped
    ports:
      - "8088:8088"
    environment:
      DATABASE_URL: postgresql+psycopg2://superset:superset@db/superset
      SUPERSET_SECRET_KEY: MiClaveSecretaSuperSegura2024xyz
    volumes:
      - ./superset_config.py:/app/pythonpath/superset_config.py
      - ./init-superset.sh:/app/init-superset.sh
    command: ["/bin/bash", "/app/init-superset.sh"]
    depends_on:
      - db
      - sqlserver

volumes:
  db_data:
  sqlserver_data: